let lessons = [ //an array of lessons with various attributes (JSON objects)
    {
        "name": "History",
        "location": "Dubai Marina",
        "price": 20,
        "availability": 5,
        "image": "../images/history.png",
        "rating": 4,
    },
    {
        "name": "Geography",
        "location": "Palm Jumeirah",
        "price": 10,
        "availability": 5,
        "image": "../images/globe.gif",
        "rating": 3,
    },
    {
        "name": "Creative Writing",
        "location": "JLT",
        "price": 30,
        "availability": 5,
        "image": "../images/cw.png",
        "rating": 5,
    },
    {
       "name": "Music",
        "location": "Downtown Dubai",
        "price": 40,
        "availability": 5,
        "image": "../images/music.gif",
        "rating": 4,
    },
    {
        "name": "Art & Design",
        "location": "Al Barsha",
        "price":20,
        "availability": 5,
        "image": "../images/paint.jpg",
        "rating": 5,
    },
    {
        "name": "Culinary art",
        "location": "Deira",
        "price": 10,
        "availability": 5,
        "image": "../images/food.png",
        "rating": 3,
    },
    {
        "name": "Swimming",
        "location": "Dubai Sports City",
        "price": 50,
        "availability": 5,
        "image": "../images/swim.png",
        "rating": 4,
    },
    {
        "name": "Psychology",
        "location": "Dubai Internet City",
        "price": 60,
        "availability": 5,
        "image": "../images/brain.jpg",
        "rating": 5,
    },
    {
        "name": "Economics",
        "location": "Dubai Media City",
        "price": 70,
        "availability": 5,
        "image": "../images/economics.png",
        "rating": 4,
    },
    {
        "name": "Robotics",
        "location": "The Lakes",
        "price": 80,
        "availability": 5,
        "image": "../images/robotic.png",
        "rating": 5,
    },
    {
        "name": "Coding",
        "location": "Rashidiya",
        "price": 90,
        "availability": 5,
        "image": "../images/coding.png",
        "rating": 5,
    },
    {
        "name": "Astronomy",
        "location": "Blue Waters",
        "price": 100,
        "availability": 5,
        "image": "../images/astroo.png",
        "rating": 5,
    },
];

